---

- find: >
    paths=/etc/yum.repo.d/
    patterns=epel.repo
  register: res

- name: epel
  become: yes
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
  when: res.matched == 0

- name: install axel downloader
  become: yes
  yum: name=axel
